{% set name = "cellconstructor" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 19ba46a35bb79b5148afb41d6395fb99bc4124e2dfdd54072848bdbbd33fc882

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - numpy
    - ase
    - scipy
    - pip
    - meson-python
    - libblas
    - liblapack
  run:
    - ase
    - scipy
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - cellconstructor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mesonepigreco/CellConstructor
  summary: Python utilities that is interfaced with ASE for atomic crystal analysis
  license: GPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jan-janssen
